/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__bitboard__bitOthello
#define __PYX_HAVE__bitboard__bitOthello

#include "Python.h"
struct OthelloGameCObject;

/* "bitboard/bitOthello.pyx":22
 * 
 * 
 * cdef public class OthelloGameC [object OthelloGameCObject, type OthelloGameCType]:             # <<<<<<<<<<<<<<
 * 
 *     # Class variables.
 */
struct OthelloGameCObject {
  PyObject_HEAD
  std::uint64_t BLACK;
  std::uint64_t WHITE;
  PyObject *board;
  int _player_clr;
  int turn;
  std::uint64_t reversible;
  int _disk_count[2];
  int _pass_cnt[2];
  int _player_auto;
  PyObject *_board_log;
  PyObject *_board_back;
};

#ifndef __PYX_HAVE_API__bitboard__bitOthello

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) OthelloGameCType;

#endif /* !__PYX_HAVE_API__bitboard__bitOthello */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbitOthello(void);
#else
PyMODINIT_FUNC PyInit_bitOthello(void);
#endif

#endif /* !__PYX_HAVE__bitboard__bitOthello */
