/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__bitboard__bitcalc
#define __PYX_HAVE__bitboard__bitcalc

#include "Python.h"
struct BitBoardCObject;

/* "bitboard/bitcalc.pxd":5
 * 
 * 
 * cdef public class BitBoardC [object BitBoardCObject, type BitBoardCType]:             # <<<<<<<<<<<<<<
 * 
 *     # Class variables.
 */
struct BitBoardCObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_8bitboard_7bitcalc_BitBoardC *__pyx_vtab;
  std::uint64_t BLACK;
  std::uint64_t WHITE;
  std::uint64_t INIT_BLACK;
  std::uint64_t INIT_WHITE;
  std::uint64_t _black_board;
  std::uint64_t _white_board;
};

#ifndef __PYX_HAVE_API__bitboard__bitcalc

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) BitBoardCType;

#endif /* !__PYX_HAVE_API__bitboard__bitcalc */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbitcalc(void);
#else
PyMODINIT_FUNC PyInit_bitcalc(void);
#endif

#endif /* !__PYX_HAVE__bitboard__bitcalc */
